### ISSUE TITLE
Produce Speedscope-compatible output

### ISSUE THREAD

**Issue by Kha** [hargoniX/FlameTC#1]
I believe it would be much easier to leverage existing flamegraph viewers than to build our own: https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources

**Comment by hargoniX** [comment]
I got a branch (https://github.com/hargoniX/FlameTC/tree/flame) that exports it to the original flamegraph collapsed stack format instead. I'll wait until you got https://github.com/leanprover/lean4/pull/2181 merged and then merge on this end. I tested it against the example trace from that PR.

**Comment by Kha** [comment]
Quick feedback from using it for https://github.com/leanprover/lean4/pull/2181#issuecomment-1500923477:
* I think it's always good to default tools like this to reading input from stdin and writing output to stdout, especially since it's a good idea to immediately gzip the verbose output format
* Do we need the microseconds or can tools also cope with fractional values?

**Comment by Kha** [comment]
I don't think your implementation is quite right yet, you're exporting inclusive times when the collapsed stack format is expected to be exclusive (i.e. individual samples). There's also a semicolon missing before the last stack entry.

**Comment by hargoniX** [comment]
- I'll look into channging it like that and also fixing the bug mentioned
- Regarding the fractional values, I tried to do that at first but speedscope refused to take such a timing value because it couldn't detect the input format anymore. So it seems integers are hardwired.
